name: 1st project

on: 
    schedule:
        - cron: "* * * * *"

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: write hello
              run: echo "hello world" 
