name: 1st project

on: push

concurrency: 
    group:  Staging
    cancel-in-progress: true

jobs:
    first_job:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name: write hello
              timeout-minutes: 10  
              run: |
                echo "hello world"
                sleep 500