name: 1st project

on: push

concurrency: 
    group:  Staging
    cancel-in-progress: true

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: write hello
              run: echo "hello world"
        