name: Manual Trigger

on: workflow_dispatch

jobs:
    Upload:
        runs-on: ubuntu-latest
        steps:
        - name: write hello
          run: echo "hello world" >> hello.txt
        - uses: actions/upload-artifact@v4
          with:
            name: Hello World
            path: hello.txt

    Download:
        needs: Upload
        runs-on: ubuntu-latest
        steps:
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              name: Hello World
              path: ./downloads
          - name: Read File
            run: cat ./downloads/hello.tx