name: Install Nodejs

on: [push, workflow_dispatch]

jobs:
    deploy:
        strategy:
            matrix:
                version: [10, 12, 14]
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.version}}
                




