name: Install Nodejs

on: workflow_dispatch

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04]
                version: [10, 12, 14]
        runs-on: ${{matrix.os}}        
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.version}}
                




